# Generated by Django 5.0.4 on 2024-04-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('translated_description_es', models.TextField()),
                ('metacritic', models.IntegerField(null=True)),
                ('released', models.DateField()),
                ('updated', models.DateTimeField()),
                ('background_image', models.URLField(null=True)),
                ('website', models.URLField(null=True)),
                ('average_rating', models.FloatField()),
                ('ratings', models.JSONField()),
                ('platforms', models.JSONField()),
                ('stores', models.JSONField()),
                ('genres', models.JSONField()),
                ('tags', models.JSONField()),
                ('publishers', models.JSONField()),
                ('esbr_ratings', models.JSONField()),
            ],
        ),
    ]
