# Generated by Django 5.0.4 on 2024-04-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchEngine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='developers',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='released',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='updated',
            field=models.DateTimeField(null=True),
        ),
    ]
