# Generated by Django 5.0.4 on 2024-04-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchEngine', '0002_game_developers_alter_game_released_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='updated',
            field=models.DateField(null=True),
        ),
    ]
