# Generated by Django 5.0.6 on 2024-05-09 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchEngine', '0003_customuser_is_activated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_activated',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
