# Generated by Django 5.0.6 on 2024-05-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchEngine', '0004_remove_customuser_is_activated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='active_code',
            field=models.IntegerField(null=True),
        ),
    ]
