# Generated by Django 5.0.6 on 2024-05-10 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchEngine', '0006_customuser_email_verified_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='search_count',
            field=models.IntegerField(default=0),
        ),
    ]
