# Generated by Django 5.0.6 on 2024-05-15 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchEngine', '0007_game_search_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
