# Generated by Django 5.0.6 on 2024-05-16 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchEngine', '0008_delete_customuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='game',
            name='website',
        ),
    ]
