# Generated by Django 5.0.6 on 2024-05-16 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchEngine', '0009_remove_game_updated_remove_game_website'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='description',
        ),
    ]
