# Generated by Django 5.0.6 on 2024-05-16 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchEngine', '0010_remove_game_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='ratings',
        ),
    ]
