# Generated by Django 5.0.4 on 2024-05-04 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamesPosts', '0002_rename_like_likes_rename_post_posts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='user',
            new_name='author',
        ),
    ]
