# Generated by Django 5.0.4 on 2024-05-04 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamesPosts', '0004_rename_comments_comment_rename_likes_like_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
