# Generated by Django 5.0.4 on 2024-05-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesPosts', '0005_remove_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='last_update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
