# Generated by Django 5.0.6 on 2024-05-16 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesPosts', '0007_comment_parent_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gamesPosts.comment'),
        ),
    ]
