# Generated by Django 5.0.6 on 2024-05-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesPosts', '0009_alter_like_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='udpate_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
