# Generated by Django 5.0.6 on 2024-05-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesPosts', '0010_comment_udpate_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='udpate_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
