# Generated by Django 5.0.6 on 2024-05-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamesPosts', '0012_rename_udpate_date_comment_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
